#!/bin/bash
# /etc/init.d/brewpi-listener

### BEGIN INIT INFO
# Provides:          brewpi-listener
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or Stops brewpi-listener
# Description:       This service is used receive upd broadcast messages and redirects the to the brewpi webapp
### END INIT INFO


case "$1" in 
    start)
        echo "Starting brewpi-listener"
        /usr/bin/python /home/brewpi/brewpi-listener/BrewPiListener.py start /etc/brewpi/BrewPiListener.cfg
        ;;
    stop)
        echo "Stopping brewpi-listener"
        /usr/bin/python /home/brewpi/brewpi-listener/BrewPiListener.py stop /etc/brewpi/BrewPiListener.cfg
        ;;
    *)
        echo "Usage: /etc/init.d/brewpi-listener start|stop"
        exit 1
        ;;
esac

exit 0
