#!/bin/bash
# /etc/init.d/oinkbrew_listener

# Copyright 2015 Oink Brew
# This file is part of Oink Brew.

# Oink Brew is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Oink Brew is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with Oink Brew Listener.
# If not, see <http://www.gnu.org/licenses/gpl.html>.
#
# @author Thomas Trageser


### BEGIN INIT INFO
# Provides:          oinkbrew_listener
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or Stops oinkbrew_listener
# Description:       This service is used receive upd broadcast messages and redirects to the oinkbrew webapp
### END INIT INFO


case "$1" in 
    start)
        echo "Starting oinkbrew_listener"
        /usr/bin/python /opt/oinkbrew/oinkbrew_listener/oinkbrew_listener.py start /etc/oinkbrew/oinkbrew_listener.cfg
        ;;
    stop)
        echo "Stopping oinkbrew_listener"
        /usr/bin/python /opt/oinkbrew/oinkbrew_listener/oinkbrew_listener.py stop /etc/oinkbrew/oinkbrew_listener.cfg
        ;;
    *)
        echo "Usage: /etc/init.d/oinkbrew_listener start|stop"
        exit 1
        ;;
esac

exit 0
